FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get -y install cron vim

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY /scripts .
COPY crontab .
COPY start-crontab.sh .
RUN chmod +x start-crontab.sh
# RUN chmod 0644 /etc/cron.d/crontab
RUN chmod 0644 crontab
RUN crontab crontab

# run cron as main process of container
CMD ["./start-crontab.sh"]